version: '3'

services:
  lea:
    build: .
    env_file: .env
    environment:
      - MYSQL_HOST=db
    ports:
      - "80:3000"
    volumes:
      - ./app:/home/node/app
      #- node_modules:/home/node/app/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      - MYSQL_HOST=db
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./leajs.sql:/docker-entrypoint-initdb.d/dump.sql
      
  test_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_HOST=test_db
    ports:
      - "3307:3306"
    volumes:
      - test_db_data:/var/lib/mysql
      - ./mind_v2.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  #node_modules:
  #app:
  #db_data:
  test_db_data:
