version: '3'

services:
  lea-js:
    image: lea-jsbrain
    container_name: lea-js
    ports:
      - "3000:3000"
    volumes:
      - .:/home/lea/app
      - node_modules:/home/node/app/node_modules
  lea:
    image: lea-httpbrain
    container_name: lea-http
    environment:
      - BRAIN_HOST=http://brain:3000/brain/
      - BRAIN_PROTOCOL=http
    ports:
      - "80:3000"
    volumes:
      - .:/home/lea/app
      - node_modules:/home/node/app/node_modules
    links:
      - brain
    depends_on:
      - brain
  brain:
    image: lea-mysqlbrain
    container_name: lea-brain
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB=$DB
    ports:
      - "8080:3000"
    volumes:
      - .:/home/brain/app
      - node_modules:/home/node/app/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB
      - MYSQL_HOST=db
    volumes:
      - db_data:/data/db

volumes:
  db_data:
  node_modules: