version: '3'

services:
  lea-js:
    image: lea-jsbrain
    container_name: lea-js
    ports:
      - "3003:3000"
    volumes:
      - js_app:/home/node/app
      - node_modules:/home/node/app/node_modules
  lea-http:
    image: lea-httpbrain
    container_name: lea-http
    environment:
      - BRAIN_HOST=http://lea:3001/brain/
      - BRAIN_PROTOCOL=http
    ports:
      - "3002:3000"
    volumes:
      - http_app:/home/node/app
      - node_modules:/home/node/app/node_modules
    links:
      - lea
    depends_on:
      - lea
  lea:
    image: lea-mysqlbrain
    container_name: lea-brain
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB=$DB
    ports:
      - "3001:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB
      - MYSQL_HOST=db
    volumes:
      - db_data:/data/db
      - ./leajs.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data:
  node_modules:
  js_app:
  http_app: